### ISSUE TITLE
I noticed you're checking for terminal character, as I did. 

### ISSUE THREAD

**Issue by ZenBoat** [micheleasara/CO516-Cpp-Solutions#1]
I was told we can use strlen() to get the string size

https://github.com/micheleasara/CO516-Cpp-Solutions/blob/89cd7bd7725a5d989c8934199a0babdd1a1d9bcb/3_words/words.cpp#L7

**Comment by micheleasara** [comment]
Good point! I probably did it at the time just to get extra practice. I will change it as soon as I can.
